import os
from datasets import load_dataset

# --- CONFIGURATION ---
MIN_LOGIC_KEYWORDS = 5
MIN_CODE_CHARS = 100
LOGIC_KEYWORDS = ['def ', 'class ', 'if ', 'for ', 'while ', 'try:', 'with ', 'return ', 'raise ']
LICENSE_FLAGS = ['copyright', 'license', 'http', 'author', 'distributed under', 'apache']

def data_v4_pipeline(example):
    content = example.get('content', "")
    if not content or len(content) < 150:
        return {"content": content, "keep": False}

    lines = content.splitlines()
    first_meaningful_line_idx = -1
    
    # --- NEW ANCHOR LOGIC ---
    # We ONLY skip '#' comments to find where the 'Content' starts.
    # Docstrings (""") are now treated as "Content Start".
    for i, line in enumerate(lines):
        clean = line.strip()
        if clean and not clean.startswith('#'):
            first_meaningful_line_idx = i
            break
    
    if first_meaningful_line_idx == -1:
        return {"content": content, "keep": False}

    # --- LICENSE DETECTION ---
    # We only check the '#' block ABOVE our meaningful start
    header_text = "\n".join(lines[:first_meaningful_line_idx]).lower()
    is_license = any(flag in header_text for flag in LICENSE_FLAGS)
    
    if is_license:
        # clean the license, but keep the meaningful start (Docstring or Code)
        cleaned_content = "\n".join(lines[first_meaningful_line_idx:])
    else:
        # No license found in the '#' block? Keep the whole thing.
        cleaned_content = content

    # --- LOGIC DENSITY & TRASH CHECK (Same as before) ---
    found_keywords = [kw for kw in LOGIC_KEYWORDS if kw in cleaned_content]
    
    # Final verdict
    keep = (
        len(found_keywords) >= MIN_LOGIC_KEYWORDS and 
        len(cleaned_content) >= MIN_CODE_CHARS and
        not "generated by" in cleaned_content.lower()
    )

    return {"content": cleaned_content, "keep": keep}

# --- EXECUTION ---
print("v3: The Precision cleaner...")

ds = load_dataset("bigcode/the-stack-smol", data_dir="data/python", split="train")

# Map the pipeline
processed_ds = ds.map(data_v4_pipeline)

# Filter based on the 'keep' flag we generated
final_ds = processed_ds.filter(lambda x: x['keep'])

print(f"Original: {len(ds)} | Cleaned: {len(final_ds)}")
print(f"Removed {len(ds) - len(final_ds)} files of noise.")

# Save to disk for the next stage (The Logic Judge)
final_ds.save_to_disk("./v3_cleaned_python")