import re
from datasets import load_dataset, concatenate_datasets

# --- CONFIGURATION ---
TARGET_SAMPLES = 250000  # We want to start with a large pool to filter down
# For TARGET_SAMPLES = 250000 I got only 2358 script which are perfect and good for model.
BATCH_SIZE = 1000

# Red flags for Legacy or Machine-Generated code
LEGACY_FLAGS = [
    'Python < 2', 'Python 2.', '__builtin__', 'import new', 
    'import types', 'from types import', 'swig', 'cython', 
    'generated by', 'autogenerated', 'protobuf'
]

def is_modern_human_code(text):
    """
    Returns False if the code smells like 2004 or a machine.
    """
    text_lower = text.lower()
    # Check for legacy/generated keywords
    if any(flag.lower() in text_lower for flag in LEGACY_FLAGS):
        return False
    
    # Check for excessive underscore variables (common in wrappers)
    # If more than 10% of the lines start with an underscore-prefixed name
    lines = text.splitlines()
    if not lines:
        return False
        
    underscore_lines = sum(1 for l in lines if l.strip().startswith('_'))
    if underscore_lines > (len(lines) * 0.3): # 30% threshold
        return False
        
    return True

def process_stream(example):
    # This combines our Modernity check with basic length requirements
    content = example.get('content', '') or example.get('text', '')
    
    if len(content) < 200 or len(content) > 10000:
        return {'keep': False}
        
    if not is_modern_human_code(content):
        return {'keep': False}
        
    return {'keep': True, 'content': content}

# --- DATA LOADING ---

print("Connecting to StarCoder and CodeParrot streams...")

# We load small subsets to ensure variety
starcoder = load_dataset(
    "bigcode/starcoderdata", 
    data_dir="python", 
    split="train", 
    streaming=True
)

codeparrot = load_dataset(
    "codeparrot/codeparrot-clean-train", 
    split="train", 
    streaming=True
)

# --- THE MIGRATION ---

final_data = []
count = 0

print(f"Filtering for the first {TARGET_SAMPLES} modern scripts...")

# We iterate through the streams
for ds in [starcoder, codeparrot]:
    for sample in ds:
        res = process_stream(sample)
        if res['keep']:
            # We only store the content to keep memory low
            final_data.append({'content': res['content']})
            count += 1
            
            if count % 1000 == 0:
                print(f"Collected {count}/{TARGET_SAMPLES}...")
                
        if count >= TARGET_SAMPLES:
            break
    if count >= TARGET_SAMPLES:
        break

# Convert to a standard dataset and save
from datasets import Dataset
new_ds = Dataset.from_list(final_data)
new_ds.save_to_disk("./raw_scripts_collection_400k")

print(f"Collection Complete. Saved {len(new_ds)} modern scripts to disk.")